package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name = "accion")
public class Accion implements java.io.Serializable {

	private long acnCodigo;
	private String acnNombre;
	private String acnDescripcion;
	private boolean acnEstado;
	private Set<RolAccion> rolAccions = new HashSet<RolAccion>(0);

	public Accion() {
	}

	public Accion(long acnCodigo, String acnNombre, String acnDescripcion, boolean acnEstado) {
		this.acnCodigo = acnCodigo;
		this.acnNombre = acnNombre;
		this.acnDescripcion = acnDescripcion;
		this.acnEstado = acnEstado;
	}

	public Accion(long acnCodigo, String acnNombre, String acnDescripcion, boolean acnEstado, Set<RolAccion> rolAccions) {
		this.acnCodigo = acnCodigo;
		this.acnNombre = acnNombre;
		this.acnDescripcion = acnDescripcion;
		this.acnEstado = acnEstado;
		this.rolAccions = rolAccions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "acn_codigo", unique = true, nullable = false)
	public long getAcnCodigo() {
		return this.acnCodigo;
	}

	public void setAcnCodigo(long acnCodigo) {
		this.acnCodigo = acnCodigo;
	}

	@Column(name = "acn_nombre", nullable = false)
	public String getAcnNombre() {
		return this.acnNombre;
	}

	public void setAcnNombre(String acnNombre) {
		this.acnNombre = acnNombre;
	}

	@Column(name = "acn_descripcion", nullable = false, length = 280)
	public String getAcnDescripcion() {
		return this.acnDescripcion;
	}

	public void setAcnDescripcion(String acnDescripcion) {
		this.acnDescripcion = acnDescripcion;
	}

	@Column(name = "acn_estado", nullable = false)
	public boolean isAcnEstado() {
		return this.acnEstado;
	}

	public void setAcnEstado(boolean acnEstado) {
		this.acnEstado = acnEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accion")
	public Set<RolAccion> getRolAccions() {
		return this.rolAccions;
	}

	public void setRolAccions(Set<RolAccion> rolAccions) {
		this.rolAccions = rolAccions;
	}

}
