package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AplicacionRecurso generated by hbm2java
 */
@Entity
@Table(name = "aplicacion_recurso")
public class AplicacionRecurso implements java.io.Serializable {

	private long aprCodigo;
	private Aplicacion aplicacion;
	private Recurso recurso;

	public AplicacionRecurso() {
	}

	public AplicacionRecurso(long aprCodigo, Aplicacion aplicacion, Recurso recurso) {
		this.aprCodigo = aprCodigo;
		this.aplicacion = aplicacion;
		this.recurso = recurso;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "apr_codigo", unique = true, nullable = false)
	public long getAprCodigo() {
		return this.aprCodigo;
	}

	public void setAprCodigo(long aprCodigo) {
		this.aprCodigo = aprCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_codigo", nullable = false)
	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rec_codigo", nullable = false)
	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

}
