package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * Aplicacion generated by hbm2java
 */
@Entity
@Table(name = "aplicacion")
@Audited
public class Aplicacion implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "app_codigo", unique = true, nullable = false)
	private long appCodigo;
	
	@Column(name = "app_nombre", nullable = false, length = 280)
	private String appNombre;
	
	@Column(name = "app_token", nullable = false, length = 360)
	private String appToken;
	
	@Column(name = "app_email_confirmed", nullable = false)
	private boolean appEmailConfirmed;
	
	@Column(name = "app_email", nullable = false)
	private String appEmail;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aplicacion")
	private Set<AplicacionRecurso> aplicacionRecursos = new HashSet<AplicacionRecurso>(0);

	public Aplicacion() {
	}

	public Aplicacion(long appCodigo, String appNombre, String appToken, boolean appEmailConfirmed, String appEmail) {
		this.appCodigo = appCodigo;
		this.appNombre = appNombre;
		this.appToken = appToken;
		this.appEmailConfirmed = appEmailConfirmed;
		this.appEmail = appEmail;
	}

	public Aplicacion(long appCodigo, String appNombre, String appToken, boolean appEmailConfirmed, String appEmail, Set<AplicacionRecurso> aplicacionRecursos) {
		this.appCodigo = appCodigo;
		this.appNombre = appNombre;
		this.appToken = appToken;
		this.appEmailConfirmed = appEmailConfirmed;
		this.appEmail = appEmail;
		this.aplicacionRecursos = aplicacionRecursos;
	}

	public long getAppCodigo() {
		return this.appCodigo;
	}

	public void setAppCodigo(long appCodigo) {
		this.appCodigo = appCodigo;
	}

	public String getAppNombre() {
		return this.appNombre;
	}

	public void setAppNombre(String appNombre) {
		this.appNombre = appNombre;
	}

	public String getAppToken() {
		return this.appToken;
	}

	public void setAppToken(String appToken) {
		this.appToken = appToken;
	}

	public boolean isAppEmailConfirmed() {
		return this.appEmailConfirmed;
	}

	public void setAppEmailConfirmed(boolean appEmailConfirmed) {
		this.appEmailConfirmed = appEmailConfirmed;
	}

	public String getAppEmail() {
		return this.appEmail;
	}

	public void setAppEmail(String appEmail) {
		this.appEmail = appEmail;
	}

	public Set<AplicacionRecurso> getAplicacionRecursos() {
		return this.aplicacionRecursos;
	}

	public void setAplicacionRecursos(Set<AplicacionRecurso> aplicacionRecursos) {
		this.aplicacionRecursos = aplicacionRecursos;
	}

}
