package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ForeignKey;
import org.hibernate.envers.Audited;


/**
 * AplicacionRecurso generated by hbm2java
 */
@SuppressWarnings("deprecation")

@Entity
@Table(name = "aplicacion_recurso")
@Audited
public class AplicacionRecurso implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "apr_codigo", unique = true, nullable = false)
	private long aprCodigo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_codigo", nullable = false)
	@ForeignKey(name="Fk_aplicacion_recurso_app_codigo")
	private Aplicacion aplicacion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rec_codigo", nullable = false)
	@ForeignKey(name="Fk_aplicacion_recurso_rec_codigo")
	private Recurso recurso;

	public AplicacionRecurso() {
	}

	public AplicacionRecurso(long aprCodigo, Aplicacion aplicacion, Recurso recurso) {
		this.aprCodigo = aprCodigo;
		this.aplicacion = aplicacion;
		this.recurso = recurso;
	}

	public long getAprCodigo() {
		return this.aprCodigo;
	}

	public void setAprCodigo(long aprCodigo) {
		this.aprCodigo = aprCodigo;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

}
