package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ForeignKey;

/**
 * GrupoRol generated by hbm2java
 */
@Entity
@Table(name = "grupo_rol")
public class GrupoRol implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "grl_codigo", unique = true, nullable = false)
	private long grlCodigo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gpo_codigo", nullable = false)
	@ForeignKey(name="Fk_grupo_rol_gpo_codigo")
	private Grupo grupo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_codigo", nullable = false)
	@ForeignKey(name="Fk_grupo_rol_rol_codigo")
	private Rol rol;

	public GrupoRol() {
	}

	public GrupoRol(long grlCodigo, Grupo grupo, Rol rol) {
		this.grlCodigo = grlCodigo;
		this.grupo = grupo;
		this.rol = rol;
	}

	public long getGrlCodigo() {
		return this.grlCodigo;
	}

	public void setGrlCodigo(long grlCodigo) {
		this.grlCodigo = grlCodigo;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
