package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name = "recurso")
@Audited
public class Recurso implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "rec_codigo", unique = true, nullable = false)
	private long recCodigo;
	
	@Column(name = "rec_nombre", nullable = false, length = 280)
	private String recNombre;
	
	@Column(name = "rec_descripccion", nullable = false, length = 280)
	private String recDescripccion;
	
	@Column(name = "rec_path", nullable = false, length = 280)
	private String recPath;
	
	@Column(name = "rec_estado", nullable = false)
	private boolean recEstado;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recurso")
	private Set<RecursoRol> recursoRols = new HashSet<RecursoRol>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recurso")
	private Set<AplicacionRecurso> aplicacionRecursos = new HashSet<AplicacionRecurso>(0);

	public Recurso() {
	}

	public Recurso(long recCodigo, String recNombre, String recDescripccion, String recPath, boolean recEstado) {
		this.recCodigo = recCodigo;
		this.recNombre = recNombre;
		this.recDescripccion = recDescripccion;
		this.recPath = recPath;
		this.recEstado = recEstado;
	}

	public Recurso(long recCodigo, String recNombre, String recDescripccion, String recPath, boolean recEstado, Set<RecursoRol> recursoRols,
			Set<AplicacionRecurso> aplicacionRecursos) {
		this.recCodigo = recCodigo;
		this.recNombre = recNombre;
		this.recDescripccion = recDescripccion;
		this.recPath = recPath;
		this.recEstado = recEstado;
		this.recursoRols = recursoRols;
		this.aplicacionRecursos = aplicacionRecursos;
	}

	public long getRecCodigo() {
		return this.recCodigo;
	}

	public void setRecCodigo(long recCodigo) {
		this.recCodigo = recCodigo;
	}

	public String getRecNombre() {
		return this.recNombre;
	}

	public void setRecNombre(String recNombre) {
		this.recNombre = recNombre;
	}

	public String getRecDescripccion() {
		return this.recDescripccion;
	}

	public void setRecDescripccion(String recDescripccion) {
		this.recDescripccion = recDescripccion;
	}

	public String getRecPath() {
		return this.recPath;
	}

	public void setRecPath(String recPath) {
		this.recPath = recPath;
	}

	public boolean isRecEstado() {
		return this.recEstado;
	}

	public void setRecEstado(boolean recEstado) {
		this.recEstado = recEstado;
	}

	public Set<RecursoRol> getRecursoRols() {
		return this.recursoRols;
	}

	public void setRecursoRols(Set<RecursoRol> recursoRols) {
		this.recursoRols = recursoRols;
	}

	public Set<AplicacionRecurso> getAplicacionRecursos() {
		return this.aplicacionRecursos;
	}

	public void setAplicacionRecursos(Set<AplicacionRecurso> aplicacionRecursos) {
		this.aplicacionRecursos = aplicacionRecursos;
	}

}
