package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ForeignKey;

/**
 * RecursoRol generated by hbm2java
 */
@Entity
@Table(name = "recurso_rol")
public class RecursoRol implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "rrl_codigo", unique = true, nullable = false)
	private long rrlCodigo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rec_codigo", nullable = false)
	@ForeignKey(name="Fk_recurso_rol_rec_codigo")
	private Recurso recurso;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_codigo", nullable = false)
	@ForeignKey(name="Fk_recurso_rol_rol_codigo")
	private Rol rol;

	public RecursoRol() {
	}

	public RecursoRol(long rrlCodigo, Recurso recurso, Rol rol) {
		this.rrlCodigo = rrlCodigo;
		this.recurso = recurso;
		this.rol = rol;
	}

	public long getRrlCodigo() {
		return this.rrlCodigo;
	}

	public void setRrlCodigo(long rrlCodigo) {
		this.rrlCodigo = rrlCodigo;
	}

	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
