package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolAccion generated by hbm2java
 */
@Entity
@Table(name = "rol_accion")
public class RolAccion implements java.io.Serializable {

	private long ranCodigo;
	private Accion accion;
	private Rol rol;

	public RolAccion() {
	}

	public RolAccion(long ranCodigo, Accion accion, Rol rol) {
		this.ranCodigo = ranCodigo;
		this.accion = accion;
		this.rol = rol;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ran_codigo", unique = true, nullable = false)
	public long getRanCodigo() {
		return this.ranCodigo;
	}

	public void setRanCodigo(long ranCodigo) {
		this.ranCodigo = ranCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acn_codigo", nullable = false)
	public Accion getAccion() {
		return this.accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_codigo", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
