package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ForeignKey;
import org.hibernate.envers.Audited;

/**
 * RolAccion generated by hbm2java
 */
@SuppressWarnings("deprecation")

@Entity
@Table(name = "rol_accion")
@Audited
public class RolAccion implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ran_codigo", unique = true, nullable = false)
	private long ranCodigo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acn_codigo", nullable = false)
	@ForeignKey(name="Fk_rol_accion_acn_codigo")
	private Accion accion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_codigo", nullable = false)
	@ForeignKey(name="Fk_rol_accion_rol_codigo")
	private Rol rol;

	public RolAccion() {
	}

	public RolAccion(long ranCodigo, Accion accion, Rol rol) {
		this.ranCodigo = ranCodigo;
		this.accion = accion;
		this.rol = rol;
	}

	public long getRanCodigo() {
		return this.ranCodigo;
	}

	public void setRanCodigo(long ranCodigo) {
		this.ranCodigo = ranCodigo;
	}

	public Accion getAccion() {
		return this.accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
