package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ForeignKey;

/**
 * UsuarioGrupo generated by hbm2java
 */
@Entity
@Table(name = "usuario_grupo")
public class UsuarioGrupo implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ugo_codigo", unique = true, nullable = false)
	private long ugoCodigo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gpo_codigo", nullable = false)
	@ForeignKey(name="Fk_usuario_grupo_gpo_codigo")
	private Grupo grupo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu_codigo", nullable = false)
	@ForeignKey(name="Fk_usuario_grupo_gpo_usu_codigo")
	private Usuario usuario;

	public UsuarioGrupo() {
	}

	public UsuarioGrupo(long ugoCodigo, Grupo grupo, Usuario usuario) {
		this.ugoCodigo = ugoCodigo;
		this.grupo = grupo;
		this.usuario = usuario;
	}

	public long getUgoCodigo() {
		return this.ugoCodigo;
	}

	public void setUgoCodigo(long ugoCodigo) {
		this.ugoCodigo = ugoCodigo;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
