package co.edu.proca3si.ejb.persistence.entities;
// Generated May 5, 2016 8:50:01 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "usuario_rol")
public class UsuarioRol implements java.io.Serializable {

	private long uroCodigo;
	private Rol rol;
	private Usuario usuario;

	public UsuarioRol() {
	}

	public UsuarioRol(long uroCodigo, Rol rol, Usuario usuario) {
		this.uroCodigo = uroCodigo;
		this.rol = rol;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "uro_codigo", unique = true, nullable = false)
	public long getUroCodigo() {
		return this.uroCodigo;
	}

	public void setUroCodigo(long uroCodigo) {
		this.uroCodigo = uroCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_codigo", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu_codigo", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
